# .github/workflows/deploy-dev.yml

# Name of the full CI/CD workflow for the Dev environment.
name: 'Terraform CI/CD for Dev'

# Triggers the workflow on pushes/PRs to main, or manually.
# Path filters ensure this only runs when relevant code changes.
on:
  push:
    branches:
      - main
    #paths:
    #  - 'environments/dev/**'
     # - 'modules/**'
     # - 'src/**'
     # - 'test/**'
     # - 'requirements-dev.txt'
     # - '.github/workflows/deploy-dev.yml'
  #pull_request:
   # branches:
   #   - main
    #paths:
    #  - 'environments/dev/**'
     # - 'modules/**'
     # - 'src/**'
     # - 'test/**'
     # - 'requirements-dev.txt'
     # - '.github/workflows/deploy-dev.yml'
  workflow_dispatch:

# OIDC permissions for secure AWS authentication and PR commenting.
permissions:
  id-token: write      # Required for OIDC authentication to AWS
  contents: read       # Required to checkout the repository
  pull-requests: write # Required to post plan comments on the PR

jobs:
  # JOB 1: VALIDATE AND PLAN
  # This job runs on all triggers to provide feedback on pull requests.
  validate_and_plan:
    name: 'Validate, Test, Scan & Plan'
    runs-on: ubuntu-latest
    environment: dev # Reference the 'dev' environment for secrets

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Plan

      # --- Lambda Function Test Steps ---
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 'Install Python Test Dependencies'
        run: pip install -r requirements-dev.txt
      
      - name: 'Run Pytest Unit Tests'
        run: pytest test/

      # --- Infrastructure Quality Gates ---
      - name: 'Set up Terraform'
        # CORRECTED: The owner is 'hashicorp', not 'hashcorp'.
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  1.13.1 #  version for stability

      - name: 'Install TFLint for Terraform Linting'
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: latest

      - name: 'Run TFLint'
        run: tflint --recursive
        
      - name: 'Run Trivy for IaC Security Scanning'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '1'
          format: 'table'
          severity: 'HIGH,CRITICAL'

      # --- Terraform Plan ---
      - name: 'Terraform Init'
        id: init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
      
      - name: 'Terraform Validate'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" validate -no-color

      - name: 'Terraform Plan'
        id: plan
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color -out=tfplan

      # --- Comment on Pull Request ---
      - name: 'Create Plan Output for PR Comment'
        if: github.event_name == 'pull_request'
        id: format-plan
        run: |
          PLAN_OUTPUT=$(terraform -chdir="${{ env.TF_WORKING_DIR }}" show -no-color tfplan)
          COMMENT_BODY="#### Terraform Plan for Dev Environment 📖\`\`\`terraform\n$PLAN_OUTPUT\n\`\`\`"
          echo "comment_body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Post Plan to Pull Request'
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number });
            const botComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('Terraform Plan for Dev Environment'));
            const newBody = `${{ steps.format-plan.outputs.comment_body }}`;
            if (botComment) { await github.rest.issues.updateComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: botComment.id, body: newBody }); }
            else { await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: newBody }); }

      # --- Upload Artifacts for Apply Job ---
      - name: 'Upload Terraform Plan Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 1
          
      - name: 'Upload Source Code Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: source-code-dev
          path: src/
          retention-days: 1

  # JOB 2: APPLY CHANGES TO DEV ENVIRONMENT
  deploy_to_dev:
    name: 'Deploy to Dev'
    runs-on: ubuntu-latest
    needs: validate_and_plan
    # This job only runs on a successful merge/push to the main branch.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: dev

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
        
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Apply

      - name: 'Set up Terraform'
        # CORRECTED: The owner is 'hashicorp', not 'hashcorp'.
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  1.13.1
      
      - name: 'Download Terraform Plan Artifact'
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: ${{ env.TF_WORKING_DIR }}

      - name: 'Download Source Code Artifact'
        uses: actions/download-artifact@v4
        with:
          name: source-code-dev
          path: src/

      - name: 'Terraform Init'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
        
      - name: 'Terraform Apply'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve tfplan