# .github/workflows/deploy-dev.yml

# Name of the full CI/CD workflow for the Dev environment.
name: 'backup-deploy-dev'

# Triggers the workflow on pushes/PRs to main, or manually.
# NOTE: The 'paths' filter has been removed to ensure the workflow always runs on changes to the main branch,
# preventing the "not triggering" issue you experienced.
on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# OIDC permissions for secure AWS authentication and PR commenting.
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # JOB 1: VALIDATE AND PLAN
  # This job runs on all triggers to provide feedback on pull requests.
  validate_and_plan:
    name: 'Validate, Test, Scan & Plan'
    runs-on: ubuntu-latest
    environment: dev # Use the 'dev' environment to securely access secrets.

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # BEST PRACTICE: Use a secret for the role ARN, not a hardcoded value.
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Plan

      # --- Lambda Function Test Steps ---
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v5
        with:
          # Match the Lambda runtime for consistency.
          python-version: '3.9'
      
      - name: 'Install Python Test Dependencies'
        # Use the correct requirements file for testing.
        run: pip install -r requirements-dev.txt
      
      - name: 'Run Pytest Unit Tests'
        run: pytest test/

      # --- Infrastructure Quality Gates ---
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          # Standardizing on a consistent version.
          terraform_version: 1.13.1

      - name: 'Install TFLint for Terraform Linting'
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: latest

      - name: 'Run TFLint'
        run: tflint --recursive
        
      - name: 'Run Checkov for IaC Security Scanning'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform
          soft_fail: true # Fails the build only for critical issues.

      # --- Terraform Plan ---
      - name: 'Terraform Init'
        id: init
        # Securely pass the S3 backend bucket name from secrets.
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
      
      - name: 'Terraform Validate'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" validate -no-color

      - name: 'Terraform Plan'
        id: plan
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color -out=tfplan

      # --- Comment on Pull Request ---
      - name: 'Create Plan Output for PR Comment'
        if: github.event_name == 'pull_request'
        id: format-plan
        run: |
          PLAN_OUTPUT=$(terraform -chdir="${{ env.TF_WORKING_DIR }}" show -no-color tfplan)
          COMMENT_BODY="#### Terraform Plan for Dev Environment 📖\`\`\`terraform\n$PLAN_OUTPUT\n\`\`\`"
          echo "comment_body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Post Plan to Pull Request'
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number });
            const botComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('Terraform Plan for Dev Environment'));
            const newBody = `${{ steps.format-plan.outputs.comment_body }}`;
            if (botComment) { await github.rest.issues.updateComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: botComment.id, body: newBody }); }
            else { await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: newBody }); }

      # --- Upload Artifacts for Apply Job ---
      - name: 'Upload Terraform Plan Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 1
          
      - name: 'Upload Source Code Artifact'
        # This is the correct way to handle our two Lambda functions.
        uses: actions/upload-artifact@v4
        with:
          name: source-code-dev
          path: src/
          retention-days: 1

  # JOB 2: APPLY CHANGES TO DEV ENVIRONMENT
  deploy_to_dev:
    name: 'Deploy to Dev'
    runs-on: ubuntu-latest
    needs: validate_and_plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: dev

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
        
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use a secret for the role ARN.
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Apply

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      
      - name: 'Download Terraform Plan Artifact'
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: ${{ env.TF_WORKING_DIR }}

      - name: 'Download Source Code Artifact'
        uses: actions/download-artifact@v4
        with:
          name: source-code-dev
          path: src/

      - name: 'Terraform Init'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
        
      - name: 'Terraform Apply'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve tfplan