# .github/workflows/deploy-dev.yml

name: 'Terraform CI/CD for Dev'

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate_and_plan:
    name: 'Validate, Test, Scan & Plan'
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Plan

      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 'Install Python Test Dependencies'
        run: pip install -r requirements-dev.txt
      
      # --- THIS IS THE CORRECTED STEP ---
      - name: 'Run Pytest Unit Tests'
        env:
          DYNAMODB_TABLE_NAME: "mock-table-for-testing"
          DYNAMODB_INDEX_NAME: "mock-index-for-testing"
          # Add the project root to the PYTHONPATH so imports from 'src' work correctly.
          PYTHONPATH: "." 
        run: pytest test/

      - name: 'Create Lambda Deployment Packages'
        run: |
          (cd src/image_processing && zip -r ../../environments/dev/image-processing.zip .)
          (cd src/search_by_label && zip -r ../../environments/dev/search-by-label.zip .)

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  1.13.1 #

      - name: 'Install TFLint for Terraform Linting'
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Run TFLint'
        run: tflint --recursive
        
      - name: 'Run Trivy for IaC Security Scanning'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '1'
          format: 'table'
          severity: 'HIGH,CRITICAL'

      - name: 'Terraform Init'
        id: init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
      
      - name: 'Terraform Validate'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" validate -no-color

      - name: 'Terraform Plan'
        id: plan
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" plan -no-color -out=tfplan

      - name: 'Create Plan Output for PR Comment'
        if: github.event_name == 'pull_request'
        id: format-plan
        run: |
          PLAN_OUTPUT=$(terraform -chdir="${{ env.TF_WORKING_DIR }}" show -no-color tfplan)
          COMMENT_BODY="#### Terraform Plan for Dev Environment 📖\`\`\`terraform\n$PLAN_OUTPUT\n\`\`\`"
          echo "comment_body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Post Plan to Pull Request'
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env: { PLAN_COMMENT: '${{ steps.format-plan.outputs.comment_body }}' }
        with:
          script: |
            const newBody = process.env.PLAN_COMMENT;
            const { data: comments } = await github.rest.issues.listComments({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number });
            const botComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('Terraform Plan for Dev Environment'));
            if (botComment) { await github.rest.issues.updateComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: botComment.id, body: newBody }); }
            else { await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: newBody }); }

      - name: 'Upload Terraform and Lambda Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-dev
          path: |
            ${{ env.TF_WORKING_DIR }}/tfplan
            ${{ env.TF_WORKING_DIR }}/image-processing.zip
            ${{ env.TF_WORKING_DIR }}/search-by-label.zip
          retention-days: 1

  deploy_to_dev:
    name: 'Deploy to Dev'
    runs-on: ubuntu-latest
    needs: validate_and_plan
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' # Change 'main' to 'master' if needed
    environment: dev

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_WORKING_DIR: 'environments/dev'
        
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials (OIDC)'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction #  IAM ROLE ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Apply

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  1.13.1 #
      
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-dev
          path: ${{ env.TF_WORKING_DIR }}
        
      - name: 'Terraform Init'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}"
        
      - name: 'Terraform Apply'
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" apply -auto-approve tfplan